// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jW7cOLYw+Cr86n5Akr7lcpzuGfQYaMy67STj7fx4bacH97azt2mJVcWxitKQlJ3q",
	"hoF9h33DfZIFzyElSqJ+ynGc2BYGmI5L/D08PDz/589JlK6yVDCh1WT3z4mKlmxF4Z975ypNcs2OqF6a",
	"v2OmIskzzVMx2Z0cs0wyZboRKgi1bcmcJ4xkVC9nk+kkk2nGpOYMxsuC45wuWdnbNCE6JRTHSQXRS0bU",
	"Wmm2mpF3qWZEL6kmVKwJ+8SV5mKBTa94kpBzRtJLJq8k15oJswL2ia6yhE12J9uXVG4n6WKbZtksSReT",
	"6USvM/NFacnFYnJ9XfySnv+LRXpyPZ3sZdkp/BZatmlN0jmskWZZwiNqvsK8Il9Ndn9D4Co2+VifbTr5",
	"tGUabV1SKejKQOg3N9u+64QLcOPup0Izoc1aaJK8n092f/tz8r8lm092J/+xXR7jtj3D7Vc8Ya7T9bS7",
	"7TFLqOaXeNimsWT/zrlksVkXnNzHBnhq63spLn+lEo+6cvCs/EDjmJu2NDmqNKkdxbQG7ZfikstUrJjQ",
	"5JJKTs8TRi7YeuuSJrlBGy7VlHBh1sViEudmGCJzofmKzYg5rAu2JlTEBHswGi3JKlfa4Mw501eMCbID",
	"DV785XsSLamkkWZSzSaNbbfgiQPDkUwveczkScai4WcVgKM5hSogaYmNPWNBs+vpxKBWy50rJySmVQGN",
	"nf/v//l/qzAgSSoWU6I0lZpccb0klCRMayZJKonIV+dMTgF2USo05YKIlFwtuWYqoxGbDbpqf05SwQYA",
	"6nBFF6wN3H1YfigSLtp7f7z+2H22J5rqXIUpAn4z9IASxcUiqcLY0rKYXXIEiSMRR5Jl1NKEEwNi/Odx",
	"LgT+66WUqZxMJx/EhUivxGQ6MQQiYZrFw+lKdQf+nI2P3iIa38pVNT65ZTY+lOtufPI2UgX0r2mSI+aW",
	"16cK7gM254IpQgF7Y3IJPUiuWEzO1/AmVUly9SqFL8YHwf+dM7wPlrD74xrc5yJE75v47dNPmOzjZ+I8",
	"gqSBsCG41UlQdeu4I9Xc/RuuNOCvh7a2sdkj12ylBtCe2hmWd51KSde99BO7IX5037JbOfJ3jbMOnKc5",
	"zjmTTEQsxAnZT4ZzwTueJemaxeT9/uGWgVHCqdCEm1M0FNNcrzmNNDmn0YV5qDrnDuGSv54ekqVO8tWK",
	"yvVA0pUkPhBVO9n6B6OJXq4n08kBW0gaszhAqjYmT9XVlnO0NvEmb20ToEzVBsVyDehyvdxPxZwvmnAy",
	"38wbN+eLJnrRXC/D4IVuBg5BzDL9Phy/aen24fhNP04UU5ejhbDiZ6qjAAcOPxMOfDxLGDBZXJBz+Fmx",
	"f+cGzZr7TfiK6zBvsaKf+CpfWdbAoHzGZMSEhgswt9ikzH3Js5hqRixVhTnNVMPo4lExKhDTFRdm2snu",
	"TrF5LjRbMIm8qmIJi3Qq+2jYG3rOkhPX2HTMo4gpdbqUTC3TJO4bwF/XddtBnFjIthyI+0xi+9AZ+CSW",
	"QgOcEIDnjLBPLMoN38tFx3mp1vn2quPijMCmD6f7iFvXU3MIh9hhp074pwZ/qWaLdd9ox2mSpLk+cc3r",
	"CF+ME0LzfbPnubno7IQvDLtybLauAsja2pRIT7wl0v44N8SbKL4QLCZR2ZfMZbqCA9rfCxCGjP/KpIIZ",
	"G6A/OrTfKud8ib+xmCBE8IHiqlyWZSrn5tLi1mfkhEnTkahlmifAjF8yabYSpQvB/yhGU+6hSqg22zKX",
	"RAqaoGyEnPyKrolkZlySC28EaKJm5G0qza2dp7tkqXWmdre3F1zPLn5UM56aI13lguv1tpEIJD/PdSrV",
	"dswuWbKt+GKLysjIB5HOJdumGd+CxQrEuVX8H5KpNJcRU0GSecFF3ITlL1zEQMYItrSiXgEy99Ievzw5",
	"JW4CBCtC0Dv0EpgGEFzMmcSWxUkzEWcpFxr+iBJuqKbKz1dcK4cvBs4zsk+FSEGyQloXz8ihIPt0xZJ9",
	"qtgXB6WBntoyIAsDc8U0jammfXfyPcDoLdMUbrJlLbt6tN4uK6tNVMHk3WwY7N54Dcv7ZlHF26Rd+UZ0",
	"w/DFG9AOYKMBDx1ZbW06EosvTyyK5yss7HSezaCnr/29uW6+gCPp+gqky5w1Eq7NSAUe/0a0wonc1fP9",
	"p6RZxozkl+YiJtTIrHIrkswAleyfHE/JKo1ZwmIjcF3k50wKppkiPAVg0ozPPH5DzS53Zp1LaBIW9inj",
	"ElUvLEpFrEKCLPRHBWpBMy5pwmOu18D9AMaUE5tp5qlcUY289vcvJk3Wezphn7SkXerf4p41jrh+f2p6",
	"YTMwoRqRiyknyBvwoqXAwRiYMwPnLM3yBH46X8Ove0eHRMGNMbCH9mbnhq7x1SrX9DxhAS0wIlKQqzwF",
	"SUaxv/6wxUSUxiwmRy/flv/+Zf/kP3aem+XMyFvHyS8ZMS/TrOA1OUuAo6c+PnQxrEgVKkdyvtYsdHGA",
	"hZXvggqRQxEjksGaZIET2AcJPpCqf+c04XPOYtCXBS9ozgPE7sPhwR2ck7cIRRchddcH+B2gbrYB1JfB",
	"m3DB1gR7efu3IipXKq9y/5WHoheBzZb7NVF3AJgaKXTYXEGOzUhfi8quRCiaZTK9pMl2zASnyfac8iSX",
	"jKhC/1Ts0rMmqBa4Ez4vDYGqSfG8puE7aodsynPTEnAkNTJ4AfNBt8uQVxSfA1xj8Q31bOZkU/+mzcgv",
	"Ir0SJPIaSkb2AHQsnpIDJrj5r4HQK8oTXNQwTsWNGVTK+tjgbSGIA8VA7Rssjy9mmvJEwQOSCkaouXLa",
	"HXeUSwkciDZn6nhXg9THHkmr6Z6o0qeSCgUznfI2I5dpRzRfMZypWJou+rIY+SKzLouGOiVUpHrJZOW0",
	"DQO0ZcYKcyLK0IvmKv6Rr6ggktEYsMm2IxzvhOHrHHToeZpru+JieUGClp7DdY9fM8HwnQ7vfuZYmdmi",
	"aIlEpQqNK6qA8pk3KyZ5htP67/pffwi+65JRFRRUyNNzydn8GcEWJevg5nyiBu10oIDoRnUCoRtpYDc0",
	"ltZugEZ9ql3BNIRyBQDK8++8LP02jQqMpoCU6ZycSiNovaKJYlNiddW+Kt58n0wn0GBj5XttdXas2q9u",
	"6NrPvt68Cs0mPlpfiRLruC9JeLtxlA4V9u6fSPVgl4bkmY+gk+XnCav/4ejGEZUKmp6sRQT/eH/JZEKz",
	"jIuF0++as/3VsLimI6odD8WRTBeSKfPtg5F8rHU2Y5Fr+jZPNM8S9v5KMBjjAHTaB8wIPVwZkcJ0GnYG",
	"L4VMk2TFhLZPqbfx1ud2SJsCaq0tCnAesyxVXKdyHYSlAWHrhwbA/Y8F8F8ljOmWE4BvDrbwR+gsEMbe",
	"ieAP/rngL0NPB/F2zhd1i+kw+8NrrgPd+5wQfinY+RMWSaZv4MFwg1n/oXUW6gYwyHJ3Ym9TYZCg6bxS",
	"fYBX2KzfN6pUVqTEdurnRf3Rg2bzbk+m5k5wlzIVLz9lBpfCnItMBWFFA4IPILxdZuw4T0ANw1dMzc6E",
	"2aRtwRX5/Tti//f7Ltkib7kw4ugu+f2738nKinjPt/7ytxnZIv9Ic9n49OJ78+mArg3Q3qZCL6stdra+",
	"3zEtgp92Xnid/8nYRX30v87OxEmeZak0coM5SGounlnq72bFTgo17DSqnp6y2WI2hWG4IEuz5GI8dsnk",
	"Gn57Zub9fev3XXJMxaLs9Xzrx98BcDsvyN5bc/Y/kr232Hr6+y4B5ZtrvDPdeWFbKw1s7c4LvSQrgCH2",
	"2f59l5xolpXL2nZ9cDH1HifogFPdy48lSMxD+6PX5Uy8RE9BAznyfOvH6c5ft158b480yJvs50qnKyQs",
	"h2Keduk36uwRqH9QhxuTCAYi9oLZAwhOWZdfvUG4QGQEyQ84yarZvsGV4MKbi8Pfq/avbLlWPKKJN96o",
	"tR5NXKOJa7tkQIaLK7bPDYxXH1vvccOzrun2FVY61eRT3/Ot28UNhJ94HX79nePH3CkBDJpdLXm0BGUG",
	"9CSDPOnMNOB4GqCj74pZXBviRONC4gyP7smww84s7AN6PW13piuFOtuk8FODS1Zb18186+rybosyp3AZ",
	"M+flAbTY/CC8qrpMhV41hQ0c/izBe6vmUBjwKKuiKbdPaSea+q8d6k8c5QOtgu/AeCsahm5/uqZ3Sg9U",
	"kQ9vA+S+pxAr1QIIr1bvM8lEzCSLW5/hY9vAPbyt4/apiavzdG5SpUkrh2E/+4yG1X7Az1EqBIusoqA4",
	"7JBXEzDrhwdhQmQ/k8MDXwdVmyGMGNjzrfd01PC94PWKWRyhdqTNrNvaE36qRCpEVMBrqVD9C95WNOF/",
	"oJ6yiCthcsUFTabFmtHfy3SbEqajtuOi8XuRrCe7Wuashpq1XU09ALYfpS83NwHhBrN8J3UoFVel7ULB",
	"3ThDTeWC6WHPpr+UU+gX1t7hkMO25I3TJOOFdQgvizIzNLa2YnqZxtUr5eu0PggGKh7QX0U6letjpirr",
	"61IPda3YG7mrWXXWAgqH5h2UXLcSdUvsarSIu27NHX8mMS9FFyDk5US3QsaDm7ZbvBkl7xirR83bAcMi",
	"MoQqVdV5lqEUH4Ry8vxGWFRbcDFF8Gsxb/BruZiWz94KC4C94XMWraOE/SNNLxyc3IZ/ZvNU+vq9vblm",
	"0vsbGxyz8zT1W5Q/bAKKylIaUwfa1FfTOoy/wLZxvDU3gXMj1iBxvW/1HtYHt3N/9i2s7fVm1y80SNu9",
	"86M1QxArabVDa1TL2wtQ1RxXf9nwDtZWXb9Htc+VVQS+h5bW06x2I0M+LOW3qisj/q5GFdBXd1z0TmKQ",
	"9GgVfqNP4rfmkzidWMF52Ak6JuP2nBlx3Pcq7LvofyX46dxeYOSyyfuTQrhqZQRXQe+I08ogGCCHKig5",
	"LPIJx+3c1E2e0vcng7fwa1WcdtsI32jz5YAvWr0GY/hWHwsNGEQt6Yu//HWXPp/NZs+GgqY6aTugCovt",
	"RuAqCFifIBBl+TDsrq7Dadliri4+p/+KrdKh9ys0Qt07KssnxaB2dUNB220yVRWbKQIbaXwz7vKfVNoH",
	"f19yzSOa3DgCM7RQP8Cz+bWcPPTVW1Dos1tk6JvvU+Jp11vIUo0o0Q4LVanBGxb5nFkz+Y1in2um+caT",
	"G7VEmLqF4PcbrCHoGRCaXqVJSG196kUZ0kjzy1JhZjVFm3IcTg8YdOausq4ba4DAG27gOuz7hhYFpFoB",
	"TtUsrXIHrS+CPRHrFz8cBjVvhBAUML1N3KLAxI/g4OtiZj0/ippXBtXR8ohqw+iqrjhPaEgy27KymYZS",
	"Hy3pbh2Gd4IneoqZQFIJ/zXSosrnc/5pSjBIcsmSZEvpdcLIIknP3WSwfpidLigXSjv/z2RNkpTGDKeA",
	"Na3opzdMLPRysvviL3+dTuwQk93J//0b3fpjb+u/n2/9bffsbOt/ZmdnZ2ffffzuf4de3f7sA8hJHqUJ",
	"jwY+Eh+8HohW1630v+1J9b/6avCwHK68xAeWyBHb1/DUWlKeoMUr0jlNSnfaz6WJliXySWOpAtiADjRN",
	"lIG7QJuGlo1HrxmqhjtkF2cAcERTojNaGTgGvZV98H6uE7b/LgwirKUVyXCXTv92IzWoGSGhSp8wJoY4",
	"U1u0QN9hJlwwgqVTwz2nCx3MjdRGGz4ARZ/KE7ApT7ixyNZASKSmzmtowABl+4JcxZtQqrjF3cC7GZVV",
	"VW/iJHwxfTD66FegMZxNud4Sah6q+RjQzkPf3Pbs4eqSyviKSgaqH3SC42JhnzZSUcbcvk3arsHFGNye",
	"OeMW7NEbpYgJ2yreg19qOBuMrw4/Sq+YZPH7+fyGQkplrd6sjW/eQgJfqyJI5VNTe1/5XNlB4HtAgKnc",
	"9mE+gu8zZ1tG7PRiHNmnLFVl+BddMKFnZ+IljZYQuRalUjKVpSLGWJaSdUU0tWrQiGb0nCdcr2dnot/b",
	"EDdRwfIoTRJMuFeo8VpZDbPIVv2weV32FpDcD5uEE+V4mrmWMbwW5jVHd1cLp4YvZDmyOe+QB8HPaarJ",
	"4cEmQ6Ez5xDK3vAfNU+ZI0oI7fAu3xeU68RRroHLqysMfYAWUGiuYlo9vnY60uCKe8zpGbQE5eGKCrrA",
	"cCigk/hmQFLHKMlj8+VqyYT73Wn/zxmJ0ythJQdD121UXRMFXbsT9OXu5TdwM0Xr4t29af/rHrDFN9JU",
	"4ppu3/JeGf42n6vKZm/2XDWH2MDmVwKsMPhlp+kBhVDO97l+P7f/9gy9N3mnKov0pgh89WcNdq5ZnKtf",
	"G8+NLzj1sEkuEZfzV0oY00QynUvBYrxwc6ajpbl+RVZLCM/plCZLTG577AYEF8ZsTvNET3b/bLxFe+Rc",
	"MnphbnTnTs7X5Mxf19mkab0ukUvVecxvYPF2Td0L16mmSYtO2Xzy3HFDMw0M9rTU71uCjhUsuqBT9wsD",
	"UE0DyFo//9qGg9SIq4veuKmNQ5Wm31isVfABt4ogeLlxAHi7ubrAxAmbZP+OuYQ4wHWR/tvpXM3w1TG7",
	"99KRp/qAK5nDrD/nsfU2rKnjai2qiffYJUtsgsz0isVmWbY1kkmJ4YqEA55mNmaxCYaFTPPs53W7ui2h",
	"5ywxfDww7xmT4EQK3SDZuTO0lvOfw3Ir+idPU/r0t72t/6Zbfzzf+tvH37aKf//P9uzjd8/+7n0coDsF",
	"lewHQS8pTwwD0ZL9EdMwelTHnREpehaX2qXqRvCB1rcjiyN83euZvpZ8ck5y0Zy3OMeN5g/ycLkfg28J",
	"2+S5oSDtiysS7Lh1FPEK6POsUxLZ3MiYvrzoUDK+LnFJTCgEaaWGQ7u0noXM3B479vmaUFTc5YLrGSkj",
	"AYsfIcnELvldYVCdwhRBU/L7Cn/AODnzwxJ/gIhAQG8P1f6++9vO1t8+np3F3z37+9lZ/JtaLcN49VJE",
	"qWHqhzjdMtsW6Rz4TANhoJrWPIV8ri5LKDdiLSbiGRyIjVMd2c7u75/tINdTL1a7zBJbT3fvWmxZbWgf",
	"Z1yOeWI71ClbYMzQi9QIJG/CttGkI9WlTddisBEX0GlMGP2/xhDARxgC2LhQm0UDNrvfblbLltwSIYGh",
	"tWmZyiesMSgIhWcPIyXJao/8oC6HRUfSqKsl00sm/RxJZEkVOWdMEDeAd+bnaZowKtCedc6Sz6k7sucy",
	"guFIoE7NsmRdZnpvia9uHJ7d50Yn5Mlag8SJ9qNu8vE9k/aduGeN/tyz32vxhQPehGobNuqf/hVVlYMf",
	"Zmh0PX5ui1mthr6atgPEJ2/Uqb+lgBQy3fAIbuASEAB8cUCzIK6Fvb+DzaqO4I0mI0vw1V3Cg2cyyCmh",
	"yTiOfuIPNXdtmGHppwHga8nRybJoiNSn0faJcn7d4CgTcAhWMkyGQ5lS/aSPCtNX+e9K4BGv+l0Nz8bw",
	"JXgGl3DPCm5Yqs5jI7gqnGmWTBCDyR4Z5yrE5LTwGQaqw468xdbU0nCzt2jQ01AyoTdiaTznrr40nz5G",
	"NXN9zjbO4NnMV8k+g/LeWk7OphKh43Rtky42b5leWTWUIYRw92ztt1cJXyw12TeEMU18ZPW8v5rFcQxx",
	"jApV2Ub6kL0cqhL6apCcb7m3IHzsH47fuNP5cFjeQjBlk1yhK20m3Vvyfx0TgyLAAyRcXGByKZjPvWAd",
	"Zv+bKnra9D01eJUTtMJgEEoAHPvRwtU5KrPv2pe2uqwK0mBtlBugBg695V3JrXDChX1o6GUyPKCalsv0",
	"rznoBoFnoG7pZnwsFWpWevrmJHzxcTEXbN25iF/YeqPJL9i6b+76ZW+BSnOJgw5+OEkYQBlc5gxzLdIb",
	"Hrq3L4NUqeS6FeRl2z3XtB36Pq9QjEwqyfPbLjALsCTIj5pXGIhHHEumCh+M3o2Tp461XKZKGwlzN0ul",
	"HhC91QGgYrHBk7+0JWJr9NfVveqWeyHtOOj/cflINSVfLCB1DDDgZgK0SSCj7yrvZpLN+Sc0NzAOKhsz",
	"3C55CvYC8DwxP6hn3gz2K811uoKc5i7O4VnYBWyUKG9ZorTZp3sfLjPigW0LvuaXaXLJYlSXDlOqFnUS",
	"R1ny1mXJluzje3jvtgqPr5rkVuXcEY6ZzRR+i2r09jzhaplKPSUrGi25YOU67fED/anGHNcyiiM58ux+",
	"zqdiH+smeMmI921lBC/lMX74UPinV39pNDxgWKy29os/ZjNGreXnWo/9ow+NoMn9ow/1MMv9ow/vzGtc",
	"NnoLUaiNvvhzvTv+WhvhgKuLRn/zY723+a3W1y9bXfGo9j40HLG9b/Ug0wOuLHfhwyb0i2ZCN9zq7O9N",
	"h7qig3Wl+xhiAeBEB1HCE2zqJZrvrg5vH833mM8dYTglFr4+9hbgdbD/2K+A7lYDVQl1IGX9tEh1j5ua",
	"Wmahlbs4KJ+MGi95CfZp6yHkChtMzWXOgbbFtsRAKhAiRVHUYem2a/e1eI5aV9qi3HafagrtS3g1Ri32",
	"V9diFwcxTHUNHO+orn6w6mqP4AYJbbEKZBfgmqksFVCpoMko1ARR17lfONpwnh75rpg3tOdXPHFPVtue",
	"4SPqW+c8lPMr6uoP3lFEs0+aPP1w+mrrRxDKakXLvEnA8ZYnrdpS0845S/UrwTzfr6BLndl+e+JN87VI",
	"tdniYRnetdnBE4XOlFPPf86Kq+BG59LPiHzFJI/I4cGMHKBbHxDes4lMU302Cd+SNGadU2dMWv4PCv7N",
	"yH+lORAPXAzG76zMVZ/TFU84lSSNNE2c6jVhFFzh/mAydXntn//1hx/g+CjaZiK+sh0wHWeozw8vnj8z",
	"1EvnPN5WTC/MfzSPLtbk3HoDkiJ934wczomhTgXEphi+U90MXAGzT0ViD2BmeeHUy7lishNa6RVUnLv1",
	"g2rDufeZV0/JsWRRIUhItrIFV1xE6zCvwsrQpVxS+fm4GLvysxNNPtoVbuZf7pORvrIZlTvX13jvXKVJ",
	"rtkRBb38n00v7IIqtPhjQxBJ4G7bCBTPI9Fa0+Ix8dzoeDg6Hvo31tyVzZwNscvtOhjCmGFJq/hUlbTg",
	"5/Emf31JqzyIQZIW0uxR0nqokpZfd63NQaTZZjPfEBtiWobb1IQWdK74mepo2VZYWUdLF9xT5o46Zy6M",
	"h8XEDj0keqckouGtdjg9wVZ6HZ3sVocllzquNAazJNbI60UGes4SV1APrihbZUmrS4z7Wsvb2YwLrUUi",
	"3kkdnXo4ePjhqQd2uv22InYnRt8YlQcn4YLWU8JAmKFJsia8DMf1rsaSXjIQtsC6HbnSz5AfgVVsy1Ab",
	"/GrZJvxv5sBUnPjn57CKG1HomyS1nbobM+g1qlKrDT2moH4uj45ZlhZyVdDnbw6lV+tVKwaUmHVDuzyk",
	"uWyJ036apVBZ0/ASq1SzZ5DUA+txDsuEa4a2bYJ7DZaqbPgJLLg+NtsJrVE6+y16fbzmupoU0RYhD5CN",
	"NBf6qIj/dSGS240ISdPGkSDEoicK/WaKLDiVcAAHoScKQ4fL2EiYsuIxWT6w7ZHILv7YlomZ84VbTVkd",
	"taVGlfvcr0Ysh6rU7G+G3sKzcswueXvSHGm/mkXnipXcUOd6GyV9isU3Zp22xVRPW+qJNZWmlUSm/aux",
	"xaosIoYmhhIKkVPTtFUo5fPOXH+gwl3lChjBFdOBANxzRtgnFuV6gwrrZm2dxFHzFbPE7Z5FB5Mn6kk1",
	"OPjJ6kk1ONjIQ0+WTz4/QPg6lIhgmJGwxI7jXEyuP4K2qfpjIGL38lcqP8fp+6W45DIV8D5fUsnBieGC",
	"rbcqZZ+4+Bfmy3JR57kwMA4m9ZC5aDV3rAygqxjqJ0qiYk2oXOQrYGRyBUnuNBUxlTEmZiVqLTT9ZJDH",
	"yFCcJbFT9yqyssWT3UyKZDyDQlULiMSbGozicL3X5IrJchEkFzGThJJzqpZkK0ILwqewk/5VKi8OeIsC",
	"2HzEjBIuN0RZ+somXMiFcBKkXegAUpeLVpJSXtvdTXCt6GYer/dZfx1mv49Xjvi6d11dtYv3KpWLS+LG",
	"DP5BBqeUaJkzc3RlCfYgzbMpJ1oez9CWG/cpbbG/FL5FT9UzYuYHYwHVYHtiSXqFZgV4hc0WFNVcWaMI",
	"/FosfbjOoqLWDxDkdm6AWiV3wRagpY1AUpICLQtQA+MeLalYIM39DDCH0ppMDVSDOFIU9u5lYBuvoce8",
	"mUX+4/T0CHN9GUoQkCroLJKBtwvTIxBnN5Rpqsn+XgvzpdRVKuM2Bgy/EusUukS7V3NdRchnMV7IoeeC",
	"Z6g2+pXJImlNwMf3gmeW77Y8LLn0OoRji3WiBgHj9M0J+p47a+WgpZvRL9h6+OgXbD188PSiLccvfLod",
	"6OeKyXYe0X3tnWuA6a6ltH2DLC21zgZKNwJXMky+MVThKEhGegUanXoCjbO3FwnYbD5HWIpiBi9L/u5K",
	"cq2Z+GxxRDbFESdNUNSxq7WISIeggnnfQ5uXhe/Ah+M3SCqjdGVI/lzbiP5zquDrjBxqKIuJbAwj/84Z",
	"ZISSdMU0KOvzaEmo2iVnk21DEbd1uu2Uvn+H1j9B6zaLb6vIUxzf3Us5DiPb6PoNVRPLypPQyY2ULT1n",
	"xltRaQDWwrmnJKJJYt7NKEkFSqlBTLqkCY8xKVsLTpnxEN+QFUxFgvlDXVfD/kYRU4XppjzqGfmgwIIA",
	"QRsGwR1mIgMMchK8XXbVjt88X7sDdtVuzFkYphpWwpTloyESYsmSDGmZxhAJu6MiM7XWWWGs2EitM/XP",
	"NYQxhyu6YG1FSAY7DTSqTNeKifw5rC7SsU9PHXWDSuC2qFGgQjfJaHQxKNNbW92nVrAc5UlS6uBLJdTh",
	"/F2qj1Dp29BHuSTMVceSJ36fJzPyTyOOKKbh215yRdfqCTrI4Ea5IlkOdglDwtcgVtd6vTNfKp2ApaQJ",
	"Vkpnn8BgJ1pyb+Ock2l9MzDqQB8VA59iHPNHbSzzkx3PgTSAHbutyNGFcd5ozrF6cJmvZt9AnQ0/fsA+",
	"cWgQfr9/uAWaFE6FtpA3/IjUfE6jAAecVdCod1Me1sGOXABM923pXxjq/iVbcKUNYQPys6JrQ7Jo46aZ",
	"jiLFJDrWKf39/mExGMjzSWoopyJWqZvKVUFBTVscSPnJH4e8sm6/wZOD3O13T64wZXxHcRyfIFmW7CYl",
	"oErHq+6wbruggbQMGg9hdvv3idK3eZ3BJa1JXwYL2G1lpr4s89QKuOnkl/ycScE0Uycskkx3g+q2ljmd",
	"KJhtqAWlXCXBjr2mk5sbS3CCgRaSYQAp1xwcQGU06hgFPvcOFT75cvipB6FeG7HtXR5SCHXAkh52Zyqv",
	"TsyV5iLSNsfHlFwtQQ9KoyXhUCZBERSSNSqDziYXbP0TKIPPJlhvgX2iqyxhmN2x0B7/lMk0ziMb9W8o",
	"fCp+ytUWo0pv7RgAcSZ/OqfRBRPgf1pc0t7crVUfgdDuIPWsczmwPlvwGwpj6SUod61DZul5RBC3VZ6U",
	"xcXeYPIT9JDS0bJUXqIxYe/dAYtn5OUq0+ttkSdJbXZlq4SZd8vGSAVqnXmj9tGpt/X2kM22WOlnJXxZ",
	"0cxs/M8Ltp7CGV+jxj+csKWJcs6TJ+ioZb54MZDOB8NqSNdCL5nmkVeKs9BG+jYBg7l4HJdU8jRXhSsD",
	"LEPNyJ5X846uUZ0J4lWKUWt/ll4dU+IWdh2OO+AiD1z9t8igGPzhXry5+ZuShK94weOWuXsBvQuNCJqY",
	"eJEbsJJbh0nICwje8wChIuuvH64OIa703zkrvPecmKdTwpWCD8gsuQxqlg/yPMwoemGAbwZXSBZ0apYp",
	"ObtEwVKwT9rdlTL/cAHufQQTZtaPUqG4AuUPjGWWZZ3UrGMAcyCzO61qpsy+neoZUnJLiN03TOKcXTkD",
	"HZ5pBiX/i0sLJ+5cK1EQrhYAQPsR7NMdbS3yn8eYEyRxkLKQtr5EXEKSWQiVYVOSi8SI5+s0x/VIFjFe",
	"gNIqICF7hiBMSrMdjFRsUXWtKBdcLA41W+2bt6DlySkwSuXnyhys4asBuew6AfD4YBoCZcBvdVExNnEH",
	"7bYCYRFFT4csjvmOLUGDmAiwrznKBmJeHc+LfbhFKZJjZQfAUwSkGcYBPWFzTXIBl0fEJF1x7VkWFZOc",
	"JvwP5NQrC4VzROMxeWoDKs5ZRHPFDPfPFXofLXMBFri0/AogsJkwoEgINHpW7kcyCzrEwPqecCOFwfFG",
	"O3FuoGkSgwaRCnK5M9v5C4lTDFExEnUxB2I5N4w4VJZUntqzjjdmZ98xpfkK1Ejf4W3jf1j/LVvsCBaB",
	"SWAK/2Ezr2RAKdvGRm0SUANZWG6thNlbMCH0ZtSesyZTG7QeYBk/m2Dep572ycfiOeAnG7psaL9rSyRS",
	"WPfKNKlAQOCVrcU5Hxru5l2q4b8vP5nHaTKdHKRMvUs1/B0M0Uan6u6qtdimqDNaEWT6a4P6/KIBobfp",
	"j02wDyiyWpplhzta1w8X894fYtedJmeHYf29pSi+qbISG9fFMOD3HEubFdOKb+YmV9kkmiQkM2+cMpQl",
	"yCoh5bcUH+oDuLcas9ZgWxSVA6ELQqS6rKR6Q06ybAykollSs0EGIpvT4pSvmNJ0lXXk0sWipuBYf2X4",
	"BQxEG55AN7a5Ljady5L5GJNnDJ9vwQSTLSbbPYJveFS8oZWwAlqoqkg5SllPRkExCnTYJkdplifUK5+G",
	"4vOMHDMabxkOeGCBnM/OHPkWxQgbLQElQJBhR4IG5jMqfH41lQsqzBNl2hmWeJFK8+dTFaUZ/oq0/VnB",
	"eE5ubOSy0TPBh+FKsKBI6YV1UE3SK/C8w8hp+N2IKEY45iLeNnOdTazc3MLsVdjVoBuMZe79BDLInxb1",
	"JJCDfqK8cB7L/laihIbZnuupjYIwqGh9fKfP2pM9htHcXhjNMJwuzibuPPYKV4ARNTB+SIH0Hu9kQbjG",
	"GLcvnMGMqyyh63fB864VPISjV0sjVaGPg2yJm2vxT8oFN8SlICiysGKm3qlX3os85/EYZPtFL/t1zy0M",
	"a3PrLaoxqv7XMVT164eqNs5jkCBVocVj4OpDDVw9MvKyV/GqwI0NfKZ6fZa9cny+JoPGmBokS9AehUlC",
	"gtqLsKvxHvk/T96/I0cpXFlwNm5zjspbOBrET8NdxqD/tauZNSCcZl0RPfXbccRkZMhSyL2n/OY0gvau",
	"4MNXvSxZ2RhbBTd4zBKq+WWLK+VxtUoZNkV7pwPZkIKTe4G+Tm/nBL93qbYCCxXW+QZ2Zto7aTa9ZNJz",
	"wSyMeRMlo20uYvZp9i817KmqeNSF9l18daD2UwvKSqSXw8oF19ZfLIiJxx0OopX4NA/mr7n2nUXBqQSd",
	"/HxvtvGZHHOzjLlZtstLtFmCFq/f7WZpKQcOc8PV71VeuPjGx/xL3wArLGvHMYgT9ij+yAc/VD64RnU6",
	"LjmkNSmdSmjNn6DKVAwLhqxnU+gNhPTjG/oan6hl2bZn6y15PuotNkv2UYXIZybbqA52t2WCnG1tL2FS",
	"H+dYRbu6n8oObpJSnpqxw8q6vM2i48poFzwuXyGX7Tkx0ksmjRAB5eDBk+fcuuGcs7m59DCxkS/IKzjP",
	"3e649/6I9q5o9rOz+D/bK1xnHcLTKSbPdDJROrc78sttqCAk0diFrqaXTHLdn1LIP+8T26lIvVpJtONG",
	"9I6pso+qvaoXuSqTBQqr4NcGzjgRpsw+7yWnPxTzdGBEQ+tayoFbm3gztrbBpXib/iX4iB4X76J5Ngj7",
	"lKXKMBqcwrb3jg79TXu1bk6w0J1Ta4SKe7vs9hOXT7Mi2ZUrO1mLaDKdnNocSe5xCUuGFdM77Ieb/ay4",
	"cK4fK5plNs/v/tGHVoqV5SE7/nRywNVFazYgri7CvdDHodVjotUD4rqg1tZEUHFNuB76urXspu/d6lpX",
	"T16kFkiY16/V0aJ5gGFG4MQP5ECKh83ReN5uoqTu1Qh5vpjnCF7LBPhy02pG3jsXUvw1A4dPe/W5chlO",
	"NuBj689XgJ1VdJUlXCwODecfLHVdvDbnTF8xJtz+CXQ1676DB6TIhdKRBqXtqKf+UQR23EWdgRy0Eirz",
	"tar5qRiwwRvYuphiBImNRSo0QzrFkGFwiLXED6Q/PhpTRi3RqCVqEjNz5TbVE3k9b1tTVA7tdEXjff3K",
	"Gh/beS2ijV9KoPajzufh6nxqNKTzYa/pfVxZj6fqWfFs28qlXQqPngyKRVGSaqokLhoJGQ5Ny6IFxr+X",
	"HcprrykXGIwU4igw3YJIDeq43tzc6Zc0WtqQyOpQ6AbqBjAL9tma7rt6t8lVhmSBdA6tRTbIJqS/VBLI",
	"wDvUjX83UL35/T9T+UZvRko7Mzo6HdR+ulpx3RZzAZFBpgFZUmXTm11RBeffEoXrBn7d4QddDO65OQfG",
	"HhJicgMdYq0QWzOwml29D3sGw0VhV1jhhTzlRdT9ecKg9KvIEwiYm+xqmbOQfs1ge5qrjglck8+Yxb42",
	"rzhL4o4HGoKNrIs2ZES0/cqbWF7xAuOczgedpwv/8QZrNjBapbrU4LFhsmSba5vZcKauhBm2Bjz6kBfZ",
	"qo0862Vw79IPQSL3E+uq33a9qo2aChulJdVssR6uramN2AEMPydMhWj5n51O2m6aZPhrPXV2XYsOKWPw",
	"jpyWaV87lT55magwbh7TgNTx9cNFB1mZw75+zuMF619EvT3k+IKkSqdLydQyTeK+MTzXobDPi8vbbU82",
	"eH/duRtAR8uUR5g0CAFjkdI+d9WT8TWqVVQI3aoTtbyl/IknJ//oSp+YSX5JNfuFrY+oUtlSUsXa8yDi",
	"d1QvqeVR0ffbSH9YWVJvmkK7cwDQ8EyFIcTxDYGbOfgp/5h7bI1fKCWa2X7NjcolSOtKjNaVEqzcVYjI",
	"tbFklg3jqN3TuRRWzjPYFtEksW9ZnIonLh8hwaB4L45o1Ap8Wa1AFKwmeJIvFgziGMH5zh5O5ArwAfyQ",
	"fZ6S54TPXVh0nQ/8/kUwim1UC9zLwuztJdYbtdVrU10t17UJzEFbxvVs8oryJJfsbGLXY5MJcFXm02Cr",
	"TK9t/D+kD6gKdWUWjj1yjNXbo4RKDMhzPqR2s4DG57mhPAwTEaSXTEoeM8LDHgWqm8S52MUCeLYI9y45",
	"m5wgU3M2MZK/t9MvjjaGwd+iIt6yIJ3cpMi33bglE4HC3qEHoW4Cbj5T1QZVQ5AfJ1nUEBpfgtGeM9pz",
	"oEft8mxm0ql3vl2rTm30sBNwoFHVE7jWYOQCv75tKHQkg5Sa9adgNBE9VBNRiCz13f2Gg3Dl7bcqmHYW",
	"YB4u73zq1GXkapkqrw6hve9z8HtM+xkiHH/IZgvaOyydrF+IsJE7dmNH3w1zqXbaGSxW7+mOtCuVlJ8F",
	"cK+oQiOBuxgDU7BsYhT4OO3BpxsYfooNWNybwfnyFfvv1GW2dWm836TorVlbg4HJH6nwI/aVdeCC2Q73",
	"3u25iMW945d722/e7++dHr5/5zJ6mh+rPDDmwDMnnUqSRowKfENcz6LwFlTdolLzKE+oJIqbk+B6ya2F",
	"hkpGpyCy2+BBsgeF7On2O3b1P/+VyospeZkb/Ns+opI7V7pc0NU5X+Rprsj3W9GSShpBMQW311rxfvL0",
	"bPL67enZZErOJh9O988mz4LkCfXUJ9GSxdYpvG4UKF9sZVu54h2pOcaIxOmVSFJqa1DFFt2Un4ZS85X7",
	"mtrk6sSWRAvwEr2q6n1ZraEEvJbUryWN2IHnaj5U56495Op8O127Bo0OEyWPJapu8bKNV3rNtU9yw3mg",
	"Wi6qG/Tjtfli7pnLy0kjAClbUZ5Mdiea0dX/MU/4Yqkjncx46vKaIEl5BV8gU6VME3LK6GpitZsT94JW",
	"ejcyGv1WHeLj01C3Z5aZsGVNUcUfJVRimK5X+TSd4+sB9IHFi7Jurc2RyCVUDjNIqDDLbsIjJlDNbne2",
	"l9FoyciL2fPGZq6urmYUPs9Sudi2fdX2m8P9l+9OXm69mD2fLfUqQVTREO9bA9Le0eFkWh7r5HKHJtmS",
	"7tj0eYJmfLI7+X72fLZj7eqAB4ah2L7c2aa5Xm5HhZp6EXpEXzMNFXMw6aZLU16aImZF0jqeisPYbDnX",
	"TksMSZQgfSXM++L5c4cbDFNnetnPt/9lVUqI9r25z8tZAPFq6TZ+MSD4YefHW5uvkJCaGXlz8Acp65Oy",
	"GK0JdAGhAVXomXsyrZ6ALdvBWs/gV9vASCS1s4AMpuEzcL3g5F1hG2BJAtXHAqMaUcYtDZgK03jJaAz2",
	"Y4ffuV6m0iW9mHrArFONj18QGdoP5xR2AtsAjLiTSX+mMXFREzDpzp3tlItyr18P+6eTv9wJoA+teI1i",
	"3UspUzn46vk5lFTr1Tt2SZaxplAtLUz10hlZqpI55kvSv0bKoRYqCOZ0WxvbivG1JTpg+b9DcEeWhtQ2",
	"+1i/gaJHTS0RVRUg2LSSFgd5B6b0z2m8/iLAQECUHIqWObu+o4MYdAgWgGkVLC2n0Iaw23+mcnF4cI1l",
	"YgLHhBw26LCqE1WP6BiTt9TOqPe9ODwobB1eT/A2zNx7UU9KBu+HrS5pXw/Yw6R+Wr2vyCNHIHu0t4NA",
	"21EZBKgwCNApulqJIpCR1uDBqkdrk0S2dlQ3x7zZTfGrJ3Pe9TSY9NPKksViDeJj1Qrn0gvluwq1oq3l",
	"6BUGsHuAEcwAkO8XczjreqMnLhP+E5vL3JpLC4/DaqJ4BwpYUAmLolJC1/WahlLf2nTdGGGlJY90md8d",
	"4gVsAn+XwRgz23Jp65VU65lBVbKiykZooUmlcsjdrRbdKqdOmQHp6G02bgPiC0ae/PRkSp78ZP4fio//",
	"r5+ekKdstphNseTKDtZc2ZlesPWL/4V/vLAqkNBOYcab7dQv4O7n9UfEKzbpVxsoKwmclpUdIMMUprFv",
	"R7RKd8LnVSyHlFU4aK1kw4quMVt/vUJ8eXEgnM8rkgAQasUMvoJMU4Hr2+Zi8kXFjlZK1sWQPWgh5IOg",
	"ViBkVt76/g5mfZXKcx7HTKDkcRdTnqD+6IMoHE4qgkfrozqEse5/WdtY7a6A/m/tZf1CnFw7CAaxdTt3",
	"tZDQ2ccjdfjS1OGH53+7C+oAX/ZTMU846uS/ear0GXLC9p+GKFwjRUuYDthz8PcqbSP2WpCSRlVp2gF0",
	"uk80bdoXotdP2g3jitBqWaWtK7ihyHznilfH6jwauvLDHUz5LtWv0lzE94TPCSoPJKNYYayUCKKOK14l",
	"Ca+ZfoT0YIH+9J9PDKYTrClgizsBC/R1JKSRZIwkIygaUR2Fyw9HyxuKRtD3EVKNrChId1tMxFBpbQum",
	"/s/NEKqSVv+OVfA3IlOjmPaQaOPdCIb3SiSchi2Ltt5DjYfbH8zDWZPjI6TIpW30zknynSnQvipRHvV3",
	"48MwPgz3QFe4TbNMpjZZavCV2YMGmNSLiXUX799k+dFDorXDnpv8Qb00WAfbB9r40ozs/0jlvyEq/xDt",
	"QjYoottZDAPd+jzDDuxQoxvY6AY2uoGNbmC36AYWwBGbX4zME7oweIJxgwwzv5rVgL9tNbhWzcg/zU4A",
	"VCkBMuJyLiJYAJKVJLJw8+1gXhiqjbAEgENSxieITRW8f1LCqB5peWXW8cQObIZ6AokDZd569b22ISwr",
	"8q19UYsQ0vjRQe5Omat3qXa1L74ZpgMv1BB/uBrz0Ob8VlSneSSebna/d+zW5s866sBGH7avRjaGCiYD",
	"vNMOnHdaL6XBlt8spenVHtU2ODqbjeqR++M54nEM7akK+u/wa6Yf1AW+Ne+wu2D8x9s73t4+J6/eGwwN",
	"H9QdHn21bpGOjLLHaJl5aNLOtDvLQz/NtF5XD4pq3gt/qk3UNHdHJUeV0EiWR7J810qo7ZhBXTZV5GcM",
	"EfUi4WVpd0JFjde3qZgqPz4w9VS5sXtB6f2TGHnjkQg/HsF+U2IomYgZ3IuO3KNoXMeGXobrhkrv2LZ5",
	"aKq9EACcF0VUFIO7Lco4bS35eSHSK1Es5FeXIzvsaQCNj6ttJ9+q4vEFXtv6LSNu8pGEjXzkt0Y6yyIv",
	"nYTTz28/3C5y4mo9jdaR0ToyMlHflHVk41vt2Uoe1L0eLSajVDgStPtB0DosFxvTs4od40FRtNGaMVKw",
	"kYLdR70WEzJNkhUTekAxnbJxJRokJI69LJoW9XTuFaGjA/NiYMwclPcShCuVV3PCQRHoTKaXPGbx1K9O",
	"ZaNtliy6ILwvPtoG5ajwJBB8A4FOXJGIKlbEA3Gng7PBVPVTgcqPUB4EStabvlNbTLI4aX8ijKmClZ8z",
	"LGfdGqyn5FdTmzWQb6S+D5v6km+L/Ja3Z4Ng5EannrjkEskHFq9odBijlcdo5TFaeYxWvjdFKxoUbIzF",
	"feTFKkIvbV9Qruh4OtsCdBs9Hk+sbnPrdxy227KA0V1zjOC9p4z9BnG9mxEr7HUfiFWvlrl922Pk76gM",
	"uD+q2DCH0h4EvNmFr2haH+xtvyeOMIMYlfHWP95b3x08vNnNh06P4O6PzjJfhv6MMtLoinzvM323kNnu",
	"ovKbUFnrsvMI6Oy9cOG5oS7qq5DYUQU2kvcx0uSbU7rdoHxD4MlovhS21wN9Ke5dgYbGForCGV/7xXAL",
	"6VcMjjR81Et827R081i+z1dv3l/H+VHJORKTR67k/CxqEFZ5PlR6MCo+R8XnSAhHxectKT4/i/K2qUEf",
	"Ku0dlaEjKziygl9crrw0k7dKj8dMS84umSK0iCbALrMzEY5wwQHvQ1TLowmcOEmlJqmMmYQoSVtwDAIZ",
	"zIb4iilNV1k1aOWJGeMJeSrYlSHNcy6Vbl0cDF5ZVIxDTXZhLZPphIl8ZdCUwl/w48fpTYM+EAfx3MwR",
	"uaiNvoCg26n99qDDob6o4sIc2xgw8uiLt8H1HfI8zRPG+oIwX5k2fYGXr3CgMdhyDLYcgy3HYMsvyR4c",
	"2sQPbTVg3aaBtrWthMY2Fa06wUG+XslVIJ3jo/3IozwBW4eUW60+x23BnNDq8QRw4nbvOGjTm3T0UhsD",
	"Nb8WxRjI5G//Cf+93tZslSVUGz5OmXat3D9wDa41KZqH2P9T2+rXstG9UJdDZXe3jMZWW9Yyt7T1M/K2",
	"j0LIKISMQsiY8cU8ADXaOUoCoyRwK+/6gAwMsausXn/6WrIu1FD1QbzyX+6Rr9vjB848pnYYjd7foFoi",
	"KCJIRmPkTYuHuZeUvGZ6pCOPjY7UT3wkKI+coAzmbgankerVjGLDb1Uz2nvtq9sbM0SNt/7BsBGQFar3",
	"/r5m+gFd3luMhXocJtKReozUozu7VC8FgXYPiIaM8VO3R0JGveoYM/XALMM9aaJ6yaUNiXpABPNeBD1t",
	"4MxyZ/Rx9JsZ6fEYw3pH2q6+nCOgdS8DXav6d0etw7Lz/Y1m/aIS9Ci8jsLr1xVe65V2h4uyD+lKjwLt",
	"KNCOtOw+0LI8yJeAvLgha+JLmQ+Jlo2y5sgRjVTkc4Qi9PwelDwj5kpzEenCQxv7FvkYSiJUXtF1xtqy",
	"bLzBme8JHTKNrON2QX2kBU4BCJmu2ix9F1zEnatyuSVsof+Pg7J/zHligxrqa0lFssawhiKqnOgl9UMX",
	"FvySCWxfeON/EVf/W1glern3rfLW3fRLlMf13kmyjpsJyuwTXWUJ9sDVvsRfgNpY6/LuxP5YBgmY25u4",
	"qwjRAJiI55LLVKyY0D9lMo3zSKMToWQLnoqfcrXFqNJbO2YDnMmfzml0wUSMJGcYcQMCMLriP/pMGoB9",
	"Q94qybJUcZ1KznryaRy7luu+pBrH/phjao0xqm2Mahuj2u5JVFtJ5cZX9JEHtBVP43pIfovA89iW5KJs",
	"+ngyXXh7vuN0F/WZR9v9mPPiq5KSjXjyTQJJBpEgbP1Nk6BepXVgo2NcyahKvj+q5Bpr0RFcMuhOv2b6",
	"QV7oe+Ip081hjDf6Ed7onoCPQbfaemk8wHs9usvcMm0ZBZfR6fjeOx3XSWhnDMggCmpddB4kDb0Xbjqb",
	"an3ulm6OWqaRWI/E+m40WtZgvBZRr5kZm56sRdRvaC7bjpbm0dI8WppHS/M9sjSXxGu0NT96W3P5QA6z",
	"NgdeyXZ7c9n4MVmcvV3fuc25PvcoD4xW569MVDbj0jczPA+iRs70/E1TowH6mMBmR/PzqC64T8aqGrfR",
	"aYAedLfBBP1AL/a9MUN3Mx3j3X6Ud7vXFD3oflsb6AO94aNB+tapzCjVjFaOB2DlqBPTHqP0IFpamKUf",
	"KDW9J6bpTdVDd01DR4XUSLpH0n37yq9cMam2V6yqBRuUrsPZASs9CSVmSMLNv1bMmtPCFusPisn3lWm/",
	"IJnxJ+qyMF1PvWQGYIRPa0t0QPV/94Fqq+O0gfA102Ay5FGl+E9Dg1DWVfpiMBlQyOdxWqDcGX6Ermjg",
	"RU4kl8lkd7I9MS+xbV0/4PfuJDFzjaGyTGi7g5lXm6HyYdLkMbyBUkH2mdR8blqzE74QXCzsk1F1DHE+",
	"CmVrha1l8cB0z4P5YYKDYuWJ3hFeCpkmyYoJ3bVCVrQatDIDSpvdhYsFYZfmpP3hzA+9S6tm+PL7Y0Kj",
	"TZZgU7bQSKZKkZjP50wyER4dU1D0ra4tq4QdxHMz6h+pzXGoGMt7EfpG82lncLQKKRwAw4hxAGGADtoR",
	"3Q28/nj9/wcAAP//KFgrd9I4AgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
